export const DOCTORS = {
  'dr-layla-al-mansouri': {
    slug: 'dr-layla-al-mansouri',
    name: 'Dr. Layla Al Mansouri',
    image: '/Assets/FDoc 4.jpg',
    specialist: 'Dermatologist & Aesthetic Physician',
    yearsExp: 14,
    languages: ['English', 'Arabic'],
    category: 'dermatology',
    verticals: ['face-skin'],
    countries: ['UAE', 'KSA'],
    clinics: ['Dubai Marina', 'Abu Dhabi', 'Riyadh'],
    tagline: 'Specialist in pigmentation, anti-ageing, and GCC skin types',
    bio: 'Dr. Layla Al Mansouri is a board-certified dermatologist with 14 years of experience treating complex skin concerns across the GCC. She completed her fellowship in aesthetic dermatology at the American University of Beirut and holds subspecialty training in laser medicine for darker skin phototypes. Her practice focuses on evidence-based, physician-led aesthetic care tailored to the specific needs of Fitzpatrick III–VI skin tones.',
    treatments: ['laser-resurfacing', 'botox-fillers', 'microneedling', 'chemical-peels', 'laser-hair-removal'],
  },
  'dr-omar-hassan': {
    slug: 'dr-omar-hassan',
    name: 'Dr. Omar Hassan',
    image: '/Assets/MDoc 2.jpg',
    specialist: 'Plastic & Reconstructive Surgeon',
    yearsExp: 18,
    languages: ['English', 'Arabic', 'French'],
    category: 'plastic-surgery',
    verticals: ['surgery'],
    countries: ['UAE'],
    clinics: ['Dubai Marina', 'Downtown Dubai'],
    tagline: 'Board-certified plastic surgeon specialising in facial rejuvenation and body contouring',
    bio: 'Dr. Omar Hassan is a dual-board certified plastic and reconstructive surgeon with 18 years of surgical experience across the UAE and Europe. He trained at the University of Paris and completed advanced fellowship training in rhinoplasty and facial anatomy. His surgical philosophy prioritises natural, proportionate results that restore rather than alter the patient\'s character.',
    treatments: ['rhinoplasty', 'face-lift', 'eyelid-surgery', 'liposuction', 'tummy-tuck', 'breast-augmentation'],
  },
  'dr-sara-qasim': {
    slug: 'dr-sara-qasim',
    name: 'Dr. Sara Qasim',
    image: '/Assets/FDoc 1.jpg',
    specialist: 'Longevity & Functional Medicine Physician',
    yearsExp: 11,
    languages: ['English', 'Arabic', 'Urdu'],
    category: 'wellness',
    verticals: ['wellness'],
    countries: ['UAE', 'OMAN'],
    clinics: ['Abu Dhabi', 'Muscat'],
    tagline: 'Integrative longevity physician focused on biomarker-driven health optimisation',
    bio: 'Dr. Sara Qasim is a functional medicine physician who bridges conventional diagnostics with evidence-based longevity interventions. She holds a Fellowship in Anti-Ageing and Regenerative Medicine and has spent 11 years helping patients across the UAE and Oman understand and improve their biological age. Her approach begins with comprehensive biomarker assessment and builds into personalised protocols combining IV therapy, peptides, and hormonal optimisation.',
    treatments: ['biomarker-testing', 'iv-drip-therapy', 'nad-therapy', 'peptide-protocols', 'hormonal-balance', 'longevity-programme'],
  },
  'dr-khalid-al-farsi': {
    slug: 'dr-khalid-al-farsi',
    name: 'Dr. Khalid Al Farsi',
    image: '/Assets/MDoc 1.jpg',
    specialist: 'Body Contouring & Slimming Specialist',
    yearsExp: 9,
    languages: ['English', 'Arabic'],
    category: 'slimming',
    verticals: ['body'],
    countries: ['UAE', 'KSA'],
    clinics: ['Dubai Marina', 'Abu Dhabi', 'Jeddah'],
    tagline: 'Non-surgical body contouring and medical weight management expert',
    bio: 'Dr. Khalid Al Farsi is a physician-specialist in non-surgical body contouring with advanced training in cryolipolysis, HIFU, and injectable fat reduction techniques. Over nine years he has developed particular expertise in combination treatment protocols that address both fat reduction and skin tightening in a single programme. He is one of the region\'s most experienced practitioners in contouring injections for the submental and periabdominal areas.',
    treatments: ['cryolipolysis', 'hifu-body', 'radiofrequency', 'contouring-injections', 'mesotherapy', 'pressotherapy'],
  },
  'dr-nadia-ibrahim': {
    slug: 'dr-nadia-ibrahim',
    name: 'Dr. Nadia Ibrahim',
    image: '/Assets/FDoc 3.jpg',
    specialist: 'Hair Restoration & Dermatology Consultant',
    yearsExp: 12,
    languages: ['English', 'Arabic'],
    category: 'dermatology',
    verticals: ['hair'],
    countries: ['KSA'],
    clinics: ['Riyadh', 'Jeddah'],
    tagline: 'GCC-focused hair loss specialist with expertise in PRP and trichology',
    bio: 'Dr. Nadia Ibrahim is a consultant dermatologist with a subspecialty focus on hair and scalp disorders. She completed her trichology training in the UK and has spent 12 years managing complex alopecia cases across Saudi Arabia. Her clinical interest extends to androgenetic alopecia in women, postpartum hair loss, and the intersection of nutritional deficiency and hair thinning — conditions highly prevalent in the GCC population.',
    treatments: ['prp-hair', 'laser-resurfacing', 'microneedling', 'chemical-peels'],
  },
  'dr-james-whitfield': {
    slug: 'dr-james-whitfield',
    name: 'Dr. James Whitfield',
    image: '/Assets/MDoc 3.jpg',
    specialist: 'Aesthetic Physician & Injectables Specialist',
    yearsExp: 16,
    languages: ['English'],
    category: 'dermatology',
    verticals: ['face-skin', 'mens'],
    countries: ['UAE'],
    clinics: ['Dubai Marina', 'DIFC'],
    tagline: 'Precision injectables and non-surgical facial rejuvenation with a medical-first approach',
    bio: 'Dr. James Whitfield is a British-trained aesthetic physician with 16 years of clinical practice, including 10 years in the UAE. He holds a Postgraduate Diploma in Aesthetic Medicine from Queen Mary University of London and has lectured extensively on facial anatomy and safe injection techniques at regional conferences. His practice is built around the principle that aesthetic outcomes should always be clinically appropriate and anatomically justified.',
    treatments: ['botox-fillers', 'chemical-peels', 'microneedling', 'laser-hair-removal', 'prp-hair'],
  },
  'dr-amira-benali': {
    slug: 'dr-amira-benali',
    name: 'Dr. Amira Benali',
    image: '/Assets/FDoc 2.jpg',
    specialist: 'Wellness & Hormonal Health Physician',
    yearsExp: 10,
    languages: ['English', 'Arabic', 'French'],
    category: 'wellness',
    verticals: ['wellness'],
    countries: ['UAE', 'KSA'],
    clinics: ['Abu Dhabi', 'Riyadh'],
    tagline: 'Hormonal health and longevity medicine specialist for women at every life stage',
    bio: 'Dr. Amira Benali is a physician specialising in women\'s hormonal health and longevity medicine. After training in Paris and London, she has spent 10 years in the Gulf focusing on perimenopause, hormonal imbalance, and the downstream effects of cortisol dysregulation on skin, weight, and wellbeing. She takes an integrative approach, combining biomarker-led diagnostics with nutritional medicine, bio-identical hormone therapy, and IV nutritional support.',
    treatments: ['hormonal-balance', 'biomarker-testing', 'iv-drip-therapy', 'peptide-protocols', 'nad-therapy'],
  },
}

export const DOCTOR_LIST = Object.values(DOCTORS)
