export const REVIEWS = [
  {
    id: 'sarah-a',
    name: 'Sarah A.',
    location: 'Dubai',
    treatment: 'Laser Skin Resurfacing',
    category: 'dermatology',
    quote: "I'd been struggling with pigmentation for years. The team at Kaya actually listened — and delivered results I wasn't expecting this quickly.",
    before: '/Assets/1 Before.jpg',
    after: '/Assets/1 After.jpg',
  },
  {
    id: 'noura-k',
    name: 'Noura K.',
    location: 'Abu Dhabi',
    treatment: 'Botox & Fillers',
    category: 'dermatology',
    quote: "Very natural-looking results. I was nervous about looking 'done' but my doctor understood exactly what I wanted — subtle and refreshed.",
    before: '/Assets/6 Before.jpg',
    after: '/Assets/6 After.jpg',
  },
  {
    id: 'fatima-h',
    name: 'Fatima H.',
    location: 'Dubai',
    treatment: 'PRP Hair Restoration',
    category: 'dermatology',
    quote: "After three sessions my hair density has visibly improved. I wish I'd done this sooner — the difference is real and my confidence is back.",
    before: '/Assets/2 Before.jpg',
    after: '/Assets/2 After.jpg',
  },
  {
    id: 'layla-r',
    name: 'Layla R.',
    location: 'Riyadh',
    treatment: 'Cryolipolysis',
    category: 'slimming',
    quote: "Three clinics, two countries — and every visit feels the same level of care. That consistency is rare.",
    before: '/Assets/3 Before.jpg',
    after: '/Assets/3 After.jpg',
  },
  {
    id: 'dana-s',
    name: 'Dana S.',
    location: 'Dubai',
    treatment: 'HIFU Body',
    category: 'slimming',
    quote: "I saw real contouring after just two sessions. No surgery, no downtime — just results. The doctor was clear about what to expect which I appreciated.",
    before: null,
    after: null,
  },
  {
    id: 'reem-a',
    name: 'Reem A.',
    location: 'Jeddah',
    treatment: 'Mesotherapy',
    category: 'slimming',
    quote: "The team tailored the protocol to my body — not a one-size-fits-all approach. I felt the difference by session four and it kept improving.",
    before: '/Assets/3 Before-1.jpg',
    after: '/Assets/3 After-1.jpg',
  },
  {
    id: 'khalid-m',
    name: 'Khalid M.',
    location: 'Abu Dhabi',
    treatment: 'Longevity Programme',
    category: 'wellness',
    quote: "The longevity programme changed how I think about my health. My doctor built a plan around my actual results, not a generic protocol.",
    before: '/Assets/placeholder.svg',
    after: '/Assets/placeholder.svg',
  },
  {
    id: 'omar-f',
    name: 'Omar F.',
    location: 'Dubai',
    treatment: 'IV Drip Therapy',
    category: 'wellness',
    quote: "I come in monthly now. The energy boost is noticeable and my biomarkers have steadily improved. It fits into my routine with zero hassle.",
    before: null,
    after: null,
  },
  {
    id: 'sara-m',
    name: 'Sara M.',
    location: 'Muscat',
    treatment: 'Hormonal Balance',
    category: 'wellness',
    quote: "Finally a clinic that took my symptoms seriously. The testing was thorough and the protocol made a real difference within the first month.",
    before: null,
    after: null,
  },
  {
    id: 'hana-j',
    name: 'Hana J.',
    location: 'Dubai',
    treatment: 'Rhinoplasty',
    category: 'plastic-surgery',
    quote: "Dr. Al-Rashidi was incredibly honest during the consultation — no overselling, just clarity. The result was exactly what I asked for.",
    before: '/Assets/8 Before.jpg',
    after: '/Assets/8 After.jpg',
  },
  {
    id: 'maya-t',
    name: 'Maya T.',
    location: 'Riyadh',
    treatment: 'Liposuction',
    category: 'plastic-surgery',
    quote: "The post-op care was just as impressive as the procedure itself. I felt supported at every step and the team was always reachable.",
    before: null,
    after: null,
  },
  {
    id: 'lina-b',
    name: 'Lina B.',
    location: 'Abu Dhabi',
    treatment: 'Face Lift',
    category: 'plastic-surgery',
    quote: "I looked in the mirror two weeks post-op and genuinely teared up. The results were beyond what I imagined and recovery was much smoother than I feared.",
    before: '/Assets/4 Before.jpg',
    after: '/Assets/4 After.jpg',
  },
]

export function getReviewsForService(serviceName, category) {
  const byName = REVIEWS.filter(r => r.treatment.toLowerCase() === serviceName.toLowerCase())
  if (byName.length >= 2) return byName.slice(0, 3)
  const byCat = REVIEWS.filter(r => r.category === category)
  if (byCat.length >= 1) return byCat.slice(0, 3)
  return REVIEWS.slice(0, 3)
}
