export const VERTICALS = [
  { id: 'face-skin', label: 'Face & Skin',      hint: 'Botox · Laser · Peels · Microneedling',  color: '#8B5FA7' },
  { id: 'body',      label: 'Body',              hint: 'Contouring · HIFU · Cryolipolysis',       color: '#4A7D5E' },
  { id: 'hair',      label: 'Hair',              hint: 'PRP · Transplant · Laser Removal',         color: '#A0762B' },
  { id: 'wellness',  label: 'Energy & Wellness', hint: 'IV Drips · NAD+ · Longevity',              color: '#3D6E8A' },
  { id: 'mens',      label: 'Mens',              hint: 'Hair · Skin · Body · Anti-aging',          color: '#2B4870' },
  { id: 'surgery',   label: 'Surgery',           hint: 'Rhinoplasty · Face Lift · Liposuction',    color: '#7A3A3A' },
]

export const VERTICAL_SERVICES = {
  'face-skin': ['laser-resurfacing', 'botox-fillers', 'chemical-peels', 'microneedling'],
  'body':      ['cryolipolysis', 'hifu-body', 'radiofrequency', 'contouring-injections', 'mesotherapy', 'pressotherapy'],
  'hair':      ['laser-hair-removal', 'prp-hair'],
  'wellness':  ['biomarker-testing', 'iv-drip-therapy', 'nad-therapy', 'peptide-protocols', 'hormonal-balance', 'longevity-programme'],
  'mens':      ['prp-hair', 'laser-hair-removal', 'botox-fillers', 'cryolipolysis', 'hormonal-balance'],
  'surgery':   ['rhinoplasty', 'liposuction', 'tummy-tuck', 'breast-augmentation', 'eyelid-surgery', 'face-lift'],
}

export const SVC_THUMB = {
  'laser-resurfacing':     'laser',
  'microneedling':         'laser',
  'laser-hair-removal':    'laser',
  'botox-fillers':         'filler',
  'chemical-peels':        'antiage',
  'rhinoplasty':           'antiage',
  'eyelid-surgery':        'antiage',
  'face-lift':             'antiage',
  'longevity-programme':   'antiage',
  'prp-hair':              'hair',
  'cryolipolysis':         'bodyc',
  'hifu-body':             'bodyc',
  'radiofrequency':        'bodyc',
  'contouring-injections': 'bodyc',
  'pressotherapy':         'bodyc',
  'liposuction':           'bodyc',
  'tummy-tuck':            'bodyc',
  'breast-augmentation':   'bodyc',
  'mesotherapy':           'iv',
  'biomarker-testing':     'iv',
  'iv-drip-therapy':       'iv',
  'nad-therapy':           'iv',
  'peptide-protocols':     'iv',
  'hormonal-balance':      'iv',
}

export const SVC_BADGE = {
  'laser-resurfacing':     'Trending',
  'botox-fillers':         'Popular',
  'microneedling':         'Popular',
  'laser-hair-removal':    'Trending',
  'prp-hair':              'New',
  'cryolipolysis':         'Trending',
  'hifu-body':             'Popular',
  'contouring-injections': 'New',
  'iv-drip-therapy':       'Trending',
  'nad-therapy':           'New',
  'peptide-protocols':     'New',
  'hormonal-balance':      'Popular',
  'biomarker-testing':     'Popular',
  'rhinoplasty':           'Popular',
  'liposuction':           'Trending',
  'breast-augmentation':   'Popular',
  'face-lift':             'Trending',
  'eyelid-surgery':        'Trending',
}

export const SERVICES = {
  // ── DERMATOLOGY ────────────────────────────────────────────
  'laser-resurfacing': {
    name: 'Laser Skin Resurfacing', tag: 'Dermatology',
    sub: 'Medical-grade fractional lasers to address pigmentation, acne scars, and uneven texture — calibrated for GCC skin types.',
    what: 'Fractional laser resurfacing delivers high-energy laser light to the skin in a controlled pattern of micro-columns, leaving surrounding tissue intact. The fractional approach means faster recovery than fully ablative lasers while still achieving significant remodelling. At Kaya, settings are calibrated specifically for Fitzpatrick III–VI skin tones common across the GCC — a critical distinction that affects both safety and outcome.',
    benefits: [
      { i: '✦', t: 'Reduces pigmentation', d: 'UV-induced darkening, melasma, and post-inflammatory hyperpigmentation all respond to fractional laser across a series of sessions.' },
      { i: '◎', t: 'Minimises scarring', d: 'Acne scars, surgical marks, and stretch marks improve as laser energy triggers deep collagen remodelling.' },
      { i: '◈', t: 'Refines texture & pores', d: 'Rough texture, enlarged pores, and fine lines are visibly improved with each treatment session.' },
      { i: '⚕', t: 'GCC-skin safe', d: 'Settings optimised for darker skin tones to reduce the risk of post-inflammatory hyperpigmentation — a key consideration in the region.' },
    ],
    mechanism: 'Each laser pulse creates a micro-wound in the skin, triggering the natural healing response. Collagen remodelling begins within 24 hours and continues for up to 3 months after each session. The fractional pattern leaves bridges of intact skin that accelerate recovery while cumulative improvements in pigmentation, texture, and firmness build with each treatment.',
    expect: { duration: '20–45 min', sessions: '3–6 sessions', interval: '4–6 weeks apart' },
    downtime: { level: 'Moderate', desc: '2–5 days of redness, warmth, and mild peeling — similar to a moderate sunburn. Most clients are socially presentable by day 5–7 with mineral coverage. Strict sun avoidance for 4–6 weeks post-treatment is essential.' },
    suitable: ['Melasma or UV-induced hyperpigmentation', 'Post-acne or injury scarring', 'Sun damage and photo-ageing', 'Enlarged pores or uneven skin texture'],
  },
  'botox-fillers': {
    name: 'Botox & Fillers', tag: 'Dermatology',
    sub: 'Physician-administered anti-ageing injectables to soften lines, restore volume, and enhance contours — without surgery.',
    what: 'Botulinum toxin (Botox) and hyaluronic acid fillers are the two most clinically validated non-surgical facial treatments available. Botox temporarily relaxes muscles to reduce dynamic wrinkles; fillers restore volume and structural definition lost with age. At Kaya, all injectables are placed by a licensed dermatologist — every unit with clinical intent, not aesthetic habit.',
    benefits: [
      { i: '◎', t: 'Softens expression lines', d: "Forehead lines, crow's feet, and frown lines are visibly reduced after a single session." },
      { i: '✦', t: 'Restores lost volume', d: 'Cheeks, lips, temples, and under-eyes can be subtly enhanced with hyaluronic acid fillers.' },
      { i: '◈', t: 'No surgery required', d: 'Minimally invasive with zero downtime in most cases — walk in and walk out.' },
      { i: '⚕', t: 'Doctor-administered only', d: 'At Kaya, all injectables are placed by a licensed dermatologist — never a nurse or aesthetician working alone.' },
    ],
    mechanism: 'Botox blocks acetylcholine at the neuromuscular junction — the signal that causes muscle contraction. The targeted muscle relaxes for 3–6 months. Hyaluronic acid fillers integrate into the tissue, binding water molecules and physically restoring volume — lasting 9–18 months depending on the product and area treated.',
    expect: { duration: '15–30 min', sessions: '1 (with 2-week review)', interval: '3–12 months' },
    downtime: { level: 'Minimal', desc: 'Occasional minor bruising or swelling at injection sites, resolving in 24–72 hours. No restrictions on activity or makeup. Most clients return to work the same day.' },
    suitable: ["Dynamic expression lines on the forehead or crow's feet", 'Volume loss in cheeks, lips, or under-eyes', 'Jawline or chin definition without surgery', 'Brow lifting or subtle facial contouring'],
  },
  'chemical-peels': {
    name: 'Chemical Peels', tag: 'Dermatology',
    sub: 'Medical-strength chemical exfoliation to address sun damage, uneven tone, and dullness — formulated for high-UV environments.',
    what: 'A chemical peel involves precise application of an acidic solution to the skin, causing controlled exfoliation of the outer damaged layers. Depth of exfoliation — superficial, medium, or deep — is determined by acid type and concentration, selected by your dermatologist based on your skin tone, concern, and history. Peels used at Kaya are formulated for darker phototypes, reducing risk in the GCC context.',
    benefits: [
      { i: '✦', t: 'Addresses hyperpigmentation', d: 'TCA and glycolic acid peels break up melanin clusters, visibly evening skin tone over a treatment series.' },
      { i: '◎', t: 'Treats acne-prone skin', d: 'Salicylic acid peels unclog pores, reduce active breakouts, and improve post-acne marks.' },
      { i: '◈', t: 'Stimulates cell renewal', d: "Controlled exfoliation accelerates the skin's natural turnover cycle, revealing smoother, fresher skin with each session." },
      { i: '⚕', t: 'Formulated for GCC skin', d: 'Peel selection accounts for darker phototypes (III–VI) to reduce the risk of post-inflammatory hyperpigmentation.' },
    ],
    mechanism: 'Acids break the bonds between dead skin cells, facilitating shedding and accelerating cell turnover. In deeper peels, collagen synthesis is also stimulated. Glycolic acid targets the epidermis; TCA reaches the superficial dermis; the physician selects depth and acid type based on your assessment findings.',
    expect: { duration: '20–40 min', sessions: '3–6 sessions', interval: '3–4 weeks apart' },
    downtime: { level: 'Mild–Moderate', desc: 'Superficial peels: 2–3 days of mild flaking and redness. Medium peels: 5–7 days of visible peeling. Strict sun avoidance is essential for 4 weeks post-peel. No active skincare products for 3–5 days.' },
    suitable: ['Uneven skin tone or hyperpigmentation', 'Acne-prone or congested skin', 'Dull or sun-damaged complexion', 'Fine lines and early photo-ageing'],
  },
  'microneedling': {
    name: 'Microneedling', tag: 'Dermatology',
    sub: "Controlled micro-injuries trigger your skin's own collagen response — refining pores, reducing lines, and improving overall skin quality.",
    what: 'Microneedling (collagen induction therapy) uses a medical-grade pen device fitted with sterile micro-needles that penetrate the skin at a controlled depth and speed. The procedure is performed on cleansed, numbed skin and takes 30–45 minutes depending on the treatment area. Optional PRP or growth factors can be applied simultaneously for enhanced collagen stimulation.',
    benefits: [
      { i: '◎', t: 'Stimulates collagen', d: 'Controlled micro-injury activates fibroblasts to produce new collagen and elastin — the building blocks of smooth, firm skin.' },
      { i: '✦', t: 'Reduces pores & texture', d: 'Enlarged pores tighten and skin surface becomes measurably smoother over a course of sessions.' },
      { i: '◈', t: 'Improves acne scarring', d: 'Acne scars and surgical scars improve as new collagen fills in depressions over a series of treatments.' },
      { i: '⚕', t: 'Minimal downtime', d: '24–48 hours of redness, similar to a light sunburn. Most clients return to work the following day.' },
    ],
    mechanism: 'Micro-wounds created by the needles trigger platelet activation and growth factor release — initiating the same healing cascade as a minor skin injury. Fibroblasts are stimulated to produce new collagen and elastin, gradually refining texture and reducing scar depth. Results accumulate with each session over a 3–6 session course.',
    expect: { duration: '30–45 min', sessions: '3–6 sessions', interval: '4–6 weeks apart' },
    downtime: { level: 'Mild', desc: '24–48 hours of redness and mild skin sensitivity, similar to a light sunburn. Most clients return to work the next day. No makeup for 24 hours post-treatment.' },
    suitable: ['Enlarged or visible pores', 'Fine lines and mild skin laxity', 'Acne scars and post-inflammatory marks', 'Dull or congested skin needing revitalisation'],
  },
  'laser-hair-removal': {
    name: 'Laser Hair Removal', tag: 'Dermatology',
    sub: 'Permanent hair reduction using Nd:YAG and Diode laser platforms — safe and effective on all skin tones including darker GCC skin.',
    what: 'Medical laser hair removal uses targeted light energy to heat and permanently damage hair follicles. At Kaya, we use Nd:YAG and Diode laser platforms — both proven safe and effective on all skin tones, including Fitzpatrick IV–VI types common across the GCC. The technology targets melanin in the hair shaft, not the surrounding skin, making it the safest option for darker complexions.',
    benefits: [
      { i: '◉', t: 'Permanent reduction', d: 'Most clients achieve 70–90% permanent reduction in hair growth after a full course of 6–8 sessions.' },
      { i: '◎', t: 'Safe on all skin tones', d: 'Nd:YAG technology is specifically suited to darker skin tones — critical for GCC patients.' },
      { i: '✦', t: 'Full body coverage', d: 'Legs, arms, underarms, bikini, face, back, and chest can all be treated in the same appointment.' },
      { i: '◈', t: 'Minimal discomfort', d: 'Integrated cooling systems reduce heat sensation. Most clients describe it as a quick warm snap.' },
    ],
    mechanism: 'Laser energy is absorbed by melanin in the hair shaft and transmitted to the follicle as heat. Sufficient thermal energy causes irreversible follicular damage, preventing regrowth. Only follicles in the active growth phase (anagen) are destroyed per session — which is why 6–8 sessions are required to address all follicles across their growth cycles.',
    expect: { duration: '15–60 min', sessions: '6–8 sessions', interval: '4–6 weeks apart' },
    downtime: { level: 'Minimal', desc: 'Mild redness and follicular swelling for 2–24 hours. Normal activity resumed immediately. Avoid sun exposure to treated areas for 2 weeks before and after each session.' },
    suitable: ['Unwanted facial or body hair', 'Ingrown hair concerns or folliculitis', 'Darker skin tones requiring Nd:YAG technology', 'Anyone seeking a long-term hair-free solution'],
  },
  'prp-hair': {
    name: 'PRP Hair Restoration', tag: 'Dermatology',
    sub: 'Platelet-rich plasma from your own blood, injected into the scalp to reactivate dormant follicles and address thinning hair.',
    what: 'PRP (Platelet-Rich Plasma) hair restoration involves drawing a small blood sample, centrifuging it to concentrate platelets and growth factors, and injecting the resulting plasma into the scalp at the thinning areas. The treatment reactivates miniaturised follicles using nothing but your own biology — no synthetic drugs, no surgery.',
    benefits: [
      { i: '✿', t: 'Reactivates dormant follicles', d: 'Growth factors in PRP reactivate follicles that have miniaturised — slowing or reversing thinning patterns.' },
      { i: '◎', t: '100% natural — your own blood', d: 'No synthetic drugs or foreign substances. PRP is derived entirely from your own blood draw.' },
      { i: '✦', t: 'Effective for both genders', d: 'PRP addresses androgenetic alopecia in men and women, as well as diffuse thinning and postpartum hair loss.' },
      { i: '⚕', t: 'No downtime', d: 'Mild scalp sensitivity for 24 hours. Most clients return to normal activity immediately.' },
    ],
    mechanism: 'Platelets contain growth factors (PDGF, VEGF, IGF-1) that stimulate vascularisation, cell proliferation, and follicular reactivation. Injected into the scalp, these factors increase blood supply to follicles, reverse miniaturisation associated with androgenetic alopecia, and extend the anagen (active growth) phase of the hair cycle.',
    expect: { duration: '45–60 min', sessions: '3–6 sessions', interval: '4–6 weeks apart' },
    downtime: { level: 'Minimal', desc: 'Mild scalp tenderness and occasional pinpoint swelling at injection sites for 24 hours. Hair washing is usually permitted after 8 hours. No activity restrictions.' },
    suitable: ['Early-to-moderate androgenetic alopecia', 'Postpartum or stress-related hair loss', 'Diffuse thinning across the scalp', 'Anyone seeking a non-surgical hair restoration option'],
  },

  // ── BODY SLIMMING ──────────────────────────────────────────
  'cryolipolysis': {
    name: 'Cryolipolysis', tag: 'Body Slimming',
    sub: 'Freeze and permanently eliminate stubborn fat cells — no surgery, no needles, no downtime.',
    what: 'Cryolipolysis (CoolSculpting technology) uses precisely controlled cooling to target and crystallise fat cells beneath the skin. The targeted fat cells undergo apoptosis (natural cell death) and are cleared by the body over 8–12 weeks. Surrounding skin, nerves, and muscle tissue are unaffected — the technology exploits the fact that fat cells are more vulnerable to cold than other tissue types.',
    benefits: [
      { i: '◉', t: 'Permanent fat reduction', d: 'Treated fat cells are permanently eliminated. Results are visible from 8 weeks and improve up to 6 months post-treatment.' },
      { i: '◎', t: 'Non-invasive', d: 'No needles, no surgery, no anaesthesia required. Walk in and walk out with normal daily activity.' },
      { i: '✦', t: 'Multiple areas', d: 'Abdomen, flanks, thighs, arms, chin, and back can all be treated in a single session using multiple applicators.' },
      { i: '◈', t: 'Clinically proven', d: 'FDA-cleared with over 8 million treatments performed globally. Outcomes are documented and reproducible.' },
    ],
    mechanism: 'The applicator draws the targeted tissue between two cooling panels and holds it at -11°C for 35–60 minutes. At this temperature, fat cell membranes crystallise and the cells undergo programmed death. Over the following weeks, the lymphatic system naturally clears the cellular debris, reducing the fat layer by 20–27% per cycle in the treated zone.',
    expect: { duration: '35–60 min per area', sessions: '1–3 per area', interval: '8–12 weeks apart' },
    downtime: { level: 'Minimal', desc: 'Temporary numbness, redness, and mild swelling in the treated area for 1–2 weeks. Most clients resume normal activity immediately. Results develop progressively over 8–12 weeks.' },
    suitable: ['Stubborn fat deposits resistant to diet and exercise', 'Flanks, abdomen, thighs, or arms with pinchable fat', 'Non-smokers at or near their goal weight', 'Anyone seeking a non-surgical fat reduction option'],
  },
  'hifu-body': {
    name: 'HIFU Body', tag: 'Body Slimming',
    sub: 'High-intensity focused ultrasound to tighten skin and reduce localised fat — no surgery, clinically validated.',
    what: 'High-Intensity Focused Ultrasound (HIFU) concentrates ultrasound energy at precise depths within the tissue, creating controlled thermal coagulation points that stimulate collagen production and destroy localised fat deposits. The procedure is non-invasive, requires no anaesthesia, and delivers dual benefits of fat reduction and skin tightening in a single treatment.',
    benefits: [
      { i: '✦', t: 'Fat reduction & skin tightening', d: 'HIFU uniquely addresses both excess fat and skin laxity simultaneously — a distinction from most body treatments.' },
      { i: '◎', t: 'Deep tissue penetration', d: 'Energy penetrates to the SMAS layer — the same layer addressed in surgical facelifts — for lasting structural improvement.' },
      { i: '◈', t: 'No downtime', d: 'Most clients return to normal activity the same day. Mild redness may occur for a few hours post-treatment.' },
      { i: '⚕', t: 'Progressive results', d: 'Collagen remodelling continues for 3–6 months after treatment, with results improving gradually over time.' },
    ],
    mechanism: "Focused ultrasound waves converge at a precise tissue depth, generating heat at 60–70°C at the focal point. This thermal energy selectively destroys fat cells and denatures collagen fibres — triggering the body's wound-healing response and stimulating fresh collagen synthesis. The overlying skin remains unaffected.",
    expect: { duration: '45–90 min', sessions: '1–2 sessions', interval: '3–6 months apart' },
    downtime: { level: 'Minimal', desc: 'Mild redness, warmth, or tingling in the treated area for a few hours. Occasional temporary swelling for 24–48 hours. Results develop over 3–6 months as new collagen forms.' },
    suitable: ['Mild to moderate skin laxity on abdomen, arms, or thighs', 'Localised fat deposits with skin looseness', 'Anyone seeking non-surgical body tightening', 'Clients maintaining a stable weight'],
  },
  'radiofrequency': {
    name: 'Radiofrequency', tag: 'Body Slimming',
    sub: 'Controlled radiofrequency energy to tighten skin, reduce cellulite, and improve body contours — no downtime.',
    what: 'Radiofrequency (RF) body treatments use electromagnetic energy to heat the dermis and subdermis. The controlled thermal effect stimulates collagen and elastin synthesis, tightens existing fibres, and improves circulation — visibly firming the skin and improving cellulite over a course of sessions. RF is safe on all skin tones and body areas.',
    benefits: [
      { i: '◎', t: 'Skin tightening', d: 'RF heating contracts existing collagen and stimulates new collagen synthesis — visibly firming loose or crepey skin.' },
      { i: '✦', t: 'Cellulite improvement', d: 'Thermal energy disrupts the fibrous bands causing cellulite dimpling and improves lymphatic drainage.' },
      { i: '◈', t: 'Circumference reduction', d: 'Repeated treatments lead to measurable reductions in body circumference as subcutaneous fat is heated and metabolised.' },
      { i: '⚕', t: 'Zero downtime', d: 'Sessions feel like a warm massage. Clients can return to work or exercise immediately after treatment.' },
    ],
    mechanism: 'RF energy oscillates at a specific frequency that generates heat as it passes through tissue resistance. The dermis is heated to 40–43°C for a sustained period. This triggers fibroblast activation, new collagen deposition, and improved microcirculation. The process is cumulative — each session builds on the last.',
    expect: { duration: '45–60 min', sessions: '6–8 sessions', interval: 'Weekly for 6–8 weeks' },
    downtime: { level: 'None', desc: 'No downtime. Mild warmth or redness in the treated area for 1–2 hours is normal and resolves spontaneously. Most clients return to exercise the same day.' },
    suitable: ['Mild to moderate skin laxity on arms, abdomen, or thighs', 'Cellulite on buttocks or thighs', 'Anyone seeking gradual, progressive body tightening', 'Clients who want zero social downtime'],
  },
  'contouring-injections': {
    name: 'Contouring Injections', tag: 'Body Slimming',
    sub: 'Targeted fat-dissolving injections to reduce small stubborn deposits — precise, physician-administered.',
    what: 'Contouring injections (mesotherapy with fat-dissolving compounds such as deoxycholic acid or phosphatidylcholine) target localised fat deposits that resist diet and exercise. The solution is injected directly into the fat layer, disrupting fat cell membranes and triggering their elimination through the lymphatic system. Best suited to small, well-defined areas.',
    benefits: [
      { i: '◉', t: 'Precise targeting', d: 'Injections can address very specific small areas — double chin, bra fat, inner knees — with millimetre precision.' },
      { i: '◎', t: 'Permanent fat reduction', d: 'Destroyed fat cells do not regenerate. Results are maintained with stable body weight.' },
      { i: '✦', t: 'No surgery or anaesthesia', d: 'Performed in clinic with topical numbing cream. No recovery period required.' },
      { i: '◈', t: 'Physician-administered', d: 'All contouring injections at Kaya are performed by a licensed physician — accuracy of placement is critical to outcome.' },
    ],
    mechanism: 'Deoxycholic acid (or similar compounds) disrupts the phospholipid bilayer of fat cell membranes, causing lysis (cell destruction). The cellular contents are released and cleared by macrophages via the lymphatic system over 4–6 weeks. Multiple small injections spaced 1–1.5 cm apart cover the target zone systematically.',
    expect: { duration: '20–30 min', sessions: '2–4 sessions', interval: '4–6 weeks apart' },
    downtime: { level: 'Mild', desc: 'Swelling, bruising, and tenderness at injection sites for 5–10 days. The treated area may feel firm for 2–3 weeks. Results visible from 6 weeks post-treatment.' },
    suitable: ['Submental (double chin) fat', 'Small stubborn fat deposits on arms, bra area, or inner knees', 'Clients at or near their goal weight', 'Anyone seeking precision contouring without surgery'],
  },
  'mesotherapy': {
    name: 'Mesotherapy', tag: 'Body Slimming',
    sub: 'Micro-injections of vitamins, enzymes, and active compounds directly into the mesoderm to improve skin quality and reduce localised fat.',
    what: 'Mesotherapy delivers a customised cocktail of vitamins, amino acids, enzymes, and active agents via multiple micro-injections into the mesoderm (middle layer of skin). For body slimming, the formula targets fat cell metabolism and improves circulation. For skin quality, it boosts hydration and collagen. The cocktail is tailored to your specific concern at each session.',
    benefits: [
      { i: '✦', t: 'Targets localised fat', d: 'Active ingredients stimulate lipolysis (fat breakdown) within the targeted tissue, aiding inch loss over a treatment course.' },
      { i: '◎', t: 'Improves skin texture', d: 'Vitamins and hyaluronic acid in the cocktail hydrate and firm the skin — improving the dimpled appearance of cellulite.' },
      { i: '◈', t: 'Boosts circulation', d: 'Improved microcirculation in the treated zone enhances lymphatic drainage and reduces fluid retention.' },
      { i: '⚕', t: 'Fully customisable', d: 'The cocktail formula is selected for your specific concern — weight loss, cellulite, skin tightening, or hair health.' },
    ],
    mechanism: 'Micro-needles penetrate to the mesoderm (2–4 mm depth), delivering actives directly where they are needed — bypassing the skin barrier that limits topical absorption. The combination of mechanical micro-trauma and active ingredient delivery stimulates local tissue response, improving circulation, stimulating collagen, and encouraging fat cell metabolism.',
    expect: { duration: '30–45 min', sessions: '6–10 sessions', interval: 'Weekly for 6–10 weeks' },
    downtime: { level: 'Minimal', desc: 'Minor redness and pinpoint swelling at injection sites for 24 hours. Bruising is rare. Most clients return to normal activity the same day. Avoid saunas and intense exercise for 24 hours.' },
    suitable: ['Cellulite on thighs, buttocks, or abdomen', 'Localised fat deposits not responding to exercise', 'Clients seeking skin quality improvement alongside slimming', 'Hair loss (scalp mesotherapy variant available)'],
  },
  'pressotherapy': {
    name: 'Pressotherapy', tag: 'Body Slimming',
    sub: 'Sequential compression therapy to stimulate lymphatic drainage, reduce fluid retention, and support body contouring results.',
    what: 'Pressotherapy uses an air compression suit that sequentially inflates and deflates chambers around the legs, abdomen, and arms, mimicking the action of a lymphatic massage. The treatment stimulates the lymphatic system, improves circulation, and accelerates the clearance of waste products — making it an effective standalone treatment for fluid retention and an excellent complement to fat reduction procedures.',
    benefits: [
      { i: '◎', t: 'Lymphatic drainage', d: 'Sequential compression moves lymphatic fluid through the system, reducing oedema and puffiness in treated areas.' },
      { i: '✦', t: 'Enhances slimming results', d: 'Accelerates clearance of dead fat cells after cryolipolysis or contouring injections — improving and speeding visible results.' },
      { i: '◈', t: 'Reduces fluid retention', d: 'Particularly effective for leg swelling, heavy legs, and fluid accumulation — common in GCC climates.' },
      { i: '⚕', t: 'Deeply relaxing', d: 'Sessions feel like a deep, rhythmic massage. Many clients describe improved sleep and energy levels after regular treatment.' },
    ],
    mechanism: 'Graded sequential compression begins at the distal extremities (feet, hands) and progresses proximally (towards the torso). This directed pressure pushes lymphatic fluid and venous blood towards the lymph nodes, mimicking and amplifying the natural pumping action of the lymphatic system. Circulation improves, toxins are cleared, and tissue congestion reduces.',
    expect: { duration: '45–60 min', sessions: '6–10 sessions', interval: '2–3 per week' },
    downtime: { level: 'None', desc: 'No downtime. Sessions are relaxing — many clients use the time to rest or read. Increased urination in the hours following treatment is normal and indicates lymphatic drainage is working.' },
    suitable: ['Fluid retention in legs or abdomen', 'Post-cryolipolysis to accelerate fat clearance', 'Heavy, tired legs from prolonged standing', 'Anyone seeking lymphatic system support'],
  },

  // ── WELLNESS & LONGEVITY ────────────────────────────────────
  'biomarker-testing': {
    name: 'Biomarker Testing', tag: 'Wellness & Longevity',
    sub: 'Comprehensive blood panels and longevity markers to understand your biological age and build a personalised health protocol.',
    what: 'Biomarker testing at Kaya goes beyond standard blood work. Our longevity panels measure over 60 markers — including hormonal levels, inflammatory markers, cardiovascular risk factors, metabolic indicators, and cellular ageing biomarkers (telomere length, oxidative stress). Results are reviewed and interpreted by a physician who uses them to design a personalised longevity plan rather than simply flagging abnormal values.',
    benefits: [
      { i: '◎', t: 'Know your biological age', d: 'Advanced markers reveal how fast your body is ageing relative to your chronological age — enabling targeted intervention.' },
      { i: '✦', t: 'Detect silent risks early', d: 'Many cardiovascular, metabolic, and hormonal imbalances are detectable years before symptoms appear.' },
      { i: '◈', t: 'Personalised protocol foundation', d: 'Results form the evidence base for your IV therapy, peptide protocols, hormonal optimisation, and nutrition recommendations.' },
      { i: '⚕', t: 'Physician-interpreted results', d: 'A Kaya physician reviews your results in a dedicated consultation — not just a lab report emailed to you.' },
    ],
    mechanism: 'A venous blood draw is sent to a certified diagnostic laboratory. Results are typically available within 5–7 working days. Your physician reviews all values in context of your health history, lifestyle, and goals — identifying patterns and priorities rather than simply checking reference ranges. A follow-up consultation outlines your personalised plan.',
    expect: { duration: '30 min (blood draw + consult)', sessions: 'Every 3–6 months', interval: 'Quarterly or biannual' },
    downtime: { level: 'None', desc: 'No downtime. Fasting for 8–12 hours before the blood draw is required for accurate metabolic and lipid markers. Results are typically available within 5–7 working days.' },
    suitable: ['Anyone over 35 seeking proactive health monitoring', 'Clients with fatigue, weight gain, or hormonal symptoms', 'Foundation step before any longevity programme', 'Athletes or high-performers seeking optimisation data'],
  },
  'iv-drip-therapy': {
    name: 'IV Drip Therapy', tag: 'Wellness & Longevity',
    sub: 'Physician-formulated intravenous vitamins and minerals — 100% bioavailability, rapid results.',
    what: 'Intravenous nutrient therapy delivers vitamins, minerals, amino acids, and antioxidants directly into the bloodstream, bypassing the digestive system entirely. This achieves 100% bioavailability — compared to 20–40% absorption from oral supplements. At Kaya, drip formulas are designed by physicians based on your biomarker results and goals. We offer targeted drips for immunity, energy, recovery, skin radiance, and detoxification.',
    benefits: [
      { i: '✦', t: '100% bioavailability', d: 'IV delivery achieves tissue concentrations that oral supplements cannot — particularly for high-dose Vitamin C, B12, and glutathione.' },
      { i: '◎', t: 'Rapid results', d: 'Most clients notice improved energy, clarity, and mood within hours of their first session.' },
      { i: '◈', t: 'Physician-formulated', d: 'Drip composition is based on your biomarker results — not a one-size menu. Formulas are adjusted as your results improve.' },
      { i: '⚕', t: 'Safe and monitored', d: 'All drips are administered in-clinic under nursing supervision. Vitals are monitored throughout each session.' },
    ],
    mechanism: 'A peripheral IV cannula is placed in the forearm. The nutrient solution infuses over 30–60 minutes directly into the venous system, reaching systemic circulation immediately. High-dose vitamins at intravenous concentrations exert direct antioxidant, immune-modulating, and metabolic effects that are not achievable via oral supplementation.',
    expect: { duration: '30–60 min', sessions: 'Weekly to monthly', interval: 'Tailored to protocol' },
    downtime: { level: 'None', desc: 'No downtime. Most clients feel energised during and after the drip. Mild bruising at the cannula site is possible. Eating a light meal beforehand is recommended.' },
    suitable: ['Chronic fatigue or low energy', 'Post-travel or post-illness recovery', 'Athletes seeking enhanced recovery and performance', 'Anyone starting a longevity or wellness programme'],
  },
  'nad-therapy': {
    name: 'NAD+ Therapy', tag: 'Wellness & Longevity',
    sub: 'Nicotinamide adenine dinucleotide — the cellular repair coenzyme that declines with age. Replenished via IV for longevity and cognitive support.',
    what: "NAD+ (Nicotinamide Adenine Dinucleotide) is a coenzyme present in every cell that drives energy production, DNA repair, and cellular regeneration. NAD+ levels decline by approximately 50% between ages 40 and 60 — contributing to fatigue, cognitive decline, and accelerated ageing. IV NAD+ therapy replenishes cellular stores at concentrations not achievable through oral precursors, supporting the sirtuins and PARP enzymes responsible for DNA repair and longevity signalling.",
    benefits: [
      { i: '✦', t: 'Cellular energy restoration', d: 'NAD+ is the primary driver of mitochondrial function. Replenishment restores energy production at the cellular level.' },
      { i: '◎', t: 'Cognitive clarity', d: 'Clients commonly report improved focus, mental sharpness, and mood within days of treatment.' },
      { i: '◈', t: 'DNA repair activation', d: 'NAD+ activates PARP enzymes responsible for repairing DNA damage — a key mechanism of cellular ageing.' },
      { i: '⚕', t: 'Longevity signalling', d: 'NAD+ activates sirtuins — the protein family linked to caloric restriction and extended healthspan in research settings.' },
    ],
    mechanism: 'IV NAD+ bypasses the rate-limiting conversion steps required by oral precursors (NMN, NR). It enters cells via the Preiss-Handler pathway and is immediately available for mitochondrial respiration and nuclear DNA repair. Sessions are administered slowly (2–4 hours) to manage the mild flushing and chest pressure that can occur with faster infusion rates.',
    expect: { duration: '2–4 hours per session', sessions: '4–10 initial sessions', interval: 'Monthly maintenance' },
    downtime: { level: 'None', desc: 'No downtime. Mild flushing, warmth, and occasional nausea during infusion are normal and managed by slowing the drip rate. Most clients work, read, or rest during the session. Effects are cumulative — benefits deepen with each session.' },
    suitable: ['Ages 35+ experiencing fatigue, brain fog, or cognitive decline', 'Anyone with significant lifestyle stressors or burnout', 'Clients on a structured longevity programme', 'High-performers seeking cognitive optimisation'],
  },
  'peptide-protocols': {
    name: 'Peptide Protocols', tag: 'Wellness & Longevity',
    sub: 'Targeted peptide therapies for cellular health, skin quality, body composition, and performance — supervised and personalised.',
    what: 'Peptides are short chains of amino acids that act as biological signals — instructing specific cells to perform specific functions. Therapeutic peptides used in longevity medicine include growth hormone secretagogues (Sermorelin, Ipamorelin), tissue repair peptides (BPC-157, TB-500), cognitive enhancers (Semax), and skin quality peptides (GHK-Cu). At Kaya, protocols are selected and supervised by physicians based on your biomarker profile and goals.',
    benefits: [
      { i: '◈', t: 'Body composition improvement', d: 'Growth hormone secretagogues increase lean muscle mass, reduce body fat, and improve recovery — without synthetic hormone replacement.' },
      { i: '✦', t: 'Tissue repair', d: 'BPC-157 and TB-500 accelerate healing of tendons, joints, and gut lining — used in athletes and those with chronic musculoskeletal issues.' },
      { i: '◎', t: 'Skin and collagen quality', d: 'GHK-Cu peptide stimulates collagen and elastin synthesis, improving skin firmness and reducing the appearance of fine lines.' },
      { i: '⚕', t: 'Physician-supervised', d: 'All peptide protocols at Kaya are prescribed and monitored by a physician. Dosing, cycle length, and combinations are evidence-based.' },
    ],
    mechanism: 'Peptides bind to specific cell receptors, triggering targeted biological responses without the broad off-target effects of synthetic hormones. Growth hormone secretagogues stimulate the pituitary to release natural GH in pulses — maintaining physiological rhythms. Repair peptides modulate inflammatory signalling and angiogenesis at injury sites. Protocols are typically 3–6 month cycles with rest periods.',
    expect: { duration: 'Ongoing protocol', sessions: '3–6 month cycles', interval: 'Physician-guided' },
    downtime: { level: 'None', desc: 'Peptides are typically self-administered via subcutaneous injection (provided as a pre-filled protocol kit). No clinic downtime. Follow-up biomarker testing at 3 months guides protocol adjustments.' },
    suitable: ['Athletes or active individuals seeking recovery and performance', 'Anyone experiencing age-related body composition changes', 'Clients on a structured longevity programme', 'Those with chronic joint, tendon, or gut issues'],
  },
  'hormonal-balance': {
    name: 'Hormonal Balance', tag: 'Wellness & Longevity',
    sub: 'Physician-managed hormonal optimisation for energy, mood, body composition, and longevity — based on your actual lab results.',
    what: 'Hormonal health is foundational to how you feel, look, and age. Declining testosterone, oestrogen, progesterone, thyroid, and cortisol levels from the mid-30s onwards drive many symptoms attributed to "normal ageing" — fatigue, weight gain, mood changes, reduced libido, and cognitive decline. Kaya\'s physicians assess the full hormonal picture through comprehensive testing and design personalised optimisation protocols, which may include lifestyle interventions, nutraceuticals, peptides, or bio-identical hormone therapy where clinically indicated.',
    benefits: [
      { i: '✦', t: 'Energy and vitality restoration', d: 'Correcting hormonal deficiencies that cause fatigue produces reliable and often rapid improvements in energy, motivation, and mood.' },
      { i: '◎', t: 'Body composition improvement', d: 'Optimised testosterone, thyroid, and growth hormone levels improve lean mass, reduce body fat, and accelerate metabolism.' },
      { i: '◈', t: 'Cognitive clarity', d: 'Oestrogen, testosterone, and thyroid hormones all affect memory, focus, and mood. Optimisation supports mental sharpness.' },
      { i: '⚕', t: 'Longevity protection', d: 'Maintaining hormonal balance within optimal ranges reduces cardiovascular, bone, and metabolic risk associated with hormonal decline.' },
    ],
    mechanism: 'Initial comprehensive hormonal panel identifies deficiencies and imbalances across sex hormones, thyroid, adrenal, and metabolic axes. The physician designs a phased protocol — starting with lifestyle, micronutrient, and peptide interventions before considering bio-identical hormonal therapy. Follow-up testing every 3 months allows precise titration. All protocols are conservative, evidence-based, and individually calibrated.',
    expect: { duration: 'Ongoing programme', sessions: 'Quarterly review consultations', interval: 'Physician-managed' },
    downtime: { level: 'None', desc: 'No clinic downtime. Initial improvement in energy and mood typically noticed within 4–8 weeks of starting a protocol. Full benefits of hormonal optimisation develop over 3–6 months of consistent treatment.' },
    suitable: ['Adults 35+ experiencing fatigue, weight gain, or mood changes', 'Women experiencing perimenopause or menopause symptoms', 'Men with low testosterone or andropause symptoms', 'Anyone on a comprehensive longevity programme'],
  },
  'longevity-programme': {
    name: 'Longevity Programme', tag: 'Wellness & Longevity',
    sub: 'A structured, physician-led programme integrating biomarker testing, IV therapy, peptides, and hormonal optimisation — designed to extend your healthspan.',
    what: "Kaya's Longevity Programme is a comprehensive, multi-month engagement that begins with full biomarker testing and a physician consultation to establish your baseline. From there, a personalised protocol is built combining IV therapy, NAD+, peptides, hormonal optimisation, and lifestyle interventions. Quarterly testing tracks progress and guides protocol refinement. The programme is designed not just to address symptoms, but to systematically reduce biological age.",
    benefits: [
      { i: '✦', t: 'Comprehensive biological assessment', d: 'Over 60 biomarkers assessed at baseline and every 3 months — tracking your biological age, not just symptoms.' },
      { i: '◎', t: 'Multi-modal intervention', d: 'IV therapy, NAD+, peptides, hormonal balance, and lifestyle combined in one coherent physician-designed protocol.' },
      { i: '◈', t: 'Tracked outcomes', d: 'Quarterly testing allows precise measurement of biological age improvement — making the programme evidence-based, not anecdotal.' },
      { i: '⚕', t: 'Dedicated physician oversight', d: 'A named physician manages your case from start to finish, adjusting protocols based on your response and test results.' },
    ],
    mechanism: 'The programme operates on a quarterly cycle: biomarker testing → physician review → protocol adjustment → implementation. Each cycle builds on the previous, with interventions becoming more targeted as baseline deficiencies are corrected and optimisation becomes the focus. Most clients see measurable improvement in key longevity markers within the first 6 months.',
    expect: { duration: '6–12 month programme', sessions: 'Quarterly physician reviews', interval: 'Ongoing, adjustable' },
    downtime: { level: 'None', desc: 'No clinic downtime. Individual interventions within the programme (IV drips, blood draws) have no recovery requirements. The programme is designed to integrate seamlessly with daily life.' },
    suitable: ['Adults 35+ committed to proactive health optimisation', 'Executives and high-performers seeking sustained peak function', 'Anyone experiencing accelerated ageing symptoms', 'Clients who have completed biomarker testing and want a managed protocol'],
  },

  // ── PLASTIC SURGERY ─────────────────────────────────────────
  'rhinoplasty': {
    name: 'Rhinoplasty', tag: 'Plastic Surgery',
    sub: 'Surgical nose reshaping to improve aesthetics, proportion, or breathing — performed by board-certified surgeons.',
    what: 'Rhinoplasty (nose reshaping surgery) addresses the size, shape, and proportions of the nose relative to the face. At Kaya, rhinoplasty is performed by board-certified plastic surgeons with subspecialty interest in facial procedures. Both open and closed techniques are used depending on the degree of change required. Structural rhinoplasty — which prioritises long-term form and function — is our standard approach.',
    benefits: [
      { i: '◎', t: 'Improved facial harmony', d: 'Rhinoplasty addresses size, tip projection, bridge height, and nostril shape — bringing the nose into proportion with other facial features.' },
      { i: '✦', t: 'Breathing improvement', d: 'Functional rhinoplasty corrects deviated septum and internal valve collapse, improving nasal airflow alongside aesthetics.' },
      { i: '◈', t: 'Long-lasting results', d: 'Surgical reshaping delivers permanent structural change — unlike non-surgical nose fillers, which require repeat treatment.' },
      { i: '⚕', t: 'Board-certified surgeons', d: 'All rhinoplasty at Kaya is performed by a board-certified plastic surgeon with proven surgical track record — not a general practitioner.' },
    ],
    mechanism: 'Open rhinoplasty uses a small external incision across the columella (the strip of tissue between the nostrils), allowing full exposure of the cartilaginous and bony structures. The surgeon reshapes, reduces, or augments the nasal framework using the patient\'s own cartilage (often from the septum or ear). Closed rhinoplasty uses internal incisions only, suited to more limited changes.',
    expect: { duration: '2–3 hours', sessions: '1 (with follow-up visits)', interval: 'Single procedure' },
    downtime: { level: 'Significant', desc: 'Splint worn for 7–10 days. Swelling and bruising around the eyes for 2–3 weeks. Most clients return to office work at 10–14 days. Final result takes 12–18 months as swelling fully resolves. No contact sports for 6 weeks.' },
    suitable: ['Adults with fully developed facial structures (over 18)', 'Those seeking nose size reduction or tip refinement', 'Patients with functional breathing impairment from structural causes', 'Anyone who has had an unsatisfactory prior rhinoplasty (revision cases accepted)'],
  },
  'liposuction': {
    name: 'Liposuction', tag: 'Plastic Surgery',
    sub: 'Surgical fat removal from specific body areas to sculpt contours and remove deposits that do not respond to diet or exercise.',
    what: 'Liposuction is a surgical procedure that removes excess fat deposits from specific body areas using a thin tube (cannula) connected to a vacuum. Modern liposuction at Kaya uses tumescent technique — the targeted area is pre-infiltrated with a saline and anaesthetic solution that swells the fat, reduces bleeding, and allows precise extraction. The procedure sculpts specific contours rather than being a weight loss solution.',
    benefits: [
      { i: '◉', t: 'Permanent fat removal', d: 'Fat cells removed by liposuction do not regenerate. With stable body weight, results are permanent.' },
      { i: '◎', t: 'Precise body sculpting', d: 'Liposuction can address small areas (such as the neck or ankles) that do not respond to non-surgical methods.' },
      { i: '✦', t: 'Multiple areas simultaneously', d: 'Flanks, abdomen, thighs, arms, and back can be treated in a single surgical session for comprehensive body contouring.' },
      { i: '⚕', t: 'Surgeon-performed', d: 'All liposuction at Kaya is performed by a board-certified plastic surgeon — cannula placement and extraction technique are the primary determinants of outcome quality.' },
    ],
    mechanism: 'After tumescent infiltration, a small incision (3–5 mm) is made at a concealed location. The cannula is passed through the fat layer in a radial pattern, dislodging and aspirating fat cells. Skilled movement creates smooth, even removal without creating irregularities. The surrounding structures (blood vessels, nerves, connective tissue) are largely preserved by the tumescent fluid.',
    expect: { duration: '1–3 hours', sessions: '1 (with follow-up visits)', interval: 'Single procedure' },
    downtime: { level: 'Moderate', desc: 'Compression garment worn for 4–6 weeks. Swelling, bruising, and tenderness for 2–3 weeks. Return to desk work at 7–10 days. Light exercise at 3 weeks, full activity at 6 weeks. Final result visible at 3–6 months as swelling resolves.' },
    suitable: ['Adults at a stable body weight with localised fat deposits', 'Areas that have not responded to diet and exercise', 'Non-smokers in good general health', 'Those with realistic expectations — liposuction sculpts, it does not replace weight loss'],
  },
  'tummy-tuck': {
    name: 'Tummy Tuck', tag: 'Plastic Surgery',
    sub: 'Abdominoplasty to remove excess skin, tighten abdominal muscles, and restore a flat, firm abdominal contour.',
    what: 'Abdominoplasty (tummy tuck) addresses two elements that cannot be corrected by exercise or liposuction alone: excess skin (from weight loss or pregnancy) and separated abdominal muscles (diastasis recti). The surgery removes excess skin and fat below the navel, repairs the muscle wall, and repositions the navel to a natural position. It is frequently combined with liposuction for comprehensive abdominal contouring.',
    benefits: [
      { i: '✦', t: 'Removes excess skin', d: 'Skin laxity after significant weight loss or multiple pregnancies cannot be corrected non-surgically. Abdominoplasty removes it definitively.' },
      { i: '◎', t: 'Repairs muscle separation', d: 'Diastasis recti (separation of the rectus muscles) causes a persistent bulge that no exercise programme can correct — direct repair restores a flat profile.' },
      { i: '◈', t: 'Comprehensive contouring', d: 'Combined with liposuction of the flanks, abdominoplasty achieves a circumferential improvement not possible with either alone.' },
      { i: '⚕', t: 'Family-complete candidates', d: 'Ideal for women who have completed childbearing — future pregnancies could stretch the repaired muscles and skin.' },
    ],
    mechanism: 'A horizontal incision is made from hip to hip, just above the pubic area. Skin and fat are elevated from the abdominal wall. The rectus muscles are sutured together at the midline (repairing diastasis). Excess skin is removed, the remaining skin is redraped, and a new opening is created for the navel. Drains are placed for 1–2 weeks to prevent fluid accumulation.',
    expect: { duration: '2–4 hours', sessions: '1 (with follow-up visits)', interval: 'Single procedure' },
    downtime: { level: 'Significant', desc: '2–3 weeks before returning to desk work. Compression garment for 6 weeks. No lifting or strenuous activity for 6 weeks. Full recovery and final result at 3–6 months. Scar fades over 12–18 months and is positioned within swimwear or underwear lines.' },
    suitable: ['Adults with excess abdominal skin from weight loss or pregnancy', 'Those with diastasis recti (muscle separation)', 'Non-smokers in good health who are at a stable body weight', 'Women who have completed their family'],
  },
  'breast-augmentation': {
    name: 'Breast Augmentation', tag: 'Plastic Surgery',
    sub: 'Surgical breast enhancement using implants or fat transfer to increase volume, improve shape, and restore lost fullness.',
    what: 'Breast augmentation at Kaya is performed using either silicone implants (the international standard for safety and aesthetics) or fat transfer (using liposuctioned fat from another body area). Implant selection — size, profile, shape — is guided by a detailed consultation taking into account your body proportions, tissue characteristics, and aesthetic goals. All implants used are CE-marked or FDA-approved. Incision placement is discussed and chosen to minimise visible scarring.',
    benefits: [
      { i: '◎', t: 'Increased volume and fullness', d: 'Implants or fat transfer restore or add breast volume — addressing asymmetry, post-pregnancy deflation, or personal preference.' },
      { i: '✦', t: 'Improved proportions', d: 'Skilled implant selection creates balanced proportions relative to your frame — the goal is a result that looks natural, not augmented.' },
      { i: '◈', t: 'Fat transfer option', d: 'For modest size increase, fat harvested from the abdomen, flanks, or thighs is transferred — avoiding implants while simultaneously slimming the donor area.' },
      { i: '⚕', t: 'Surgeon-guided implant selection', d: 'Size and implant selection is a medical decision informed by tissue assessment — not just a preference discussion. The right implant for your anatomy is not always the one you had in mind.' },
    ],
    mechanism: 'Under general anaesthesia, a pocket is created either behind the breast tissue (subglandular) or behind the pectoral muscle (submuscular — the most common approach for long-term results). The implant is placed within the pocket via an inframammary incision (most common), periareolar, or transaxillary approach. For fat transfer, liposuction fat is processed and injected in multiple layers.',
    expect: { duration: '1–2 hours', sessions: '1 (with follow-up visits)', interval: 'Single procedure' },
    downtime: { level: 'Moderate', desc: 'Return to desk work at 5–7 days. No lifting above shoulder height for 4 weeks. Supportive bra worn continuously for 6 weeks. Full recovery at 6 weeks. Implants settle into final position over 3–6 months.' },
    suitable: ['Adults seeking increased breast volume or improved symmetry', 'Women with post-pregnancy breast deflation', 'Those with significant breast asymmetry', 'Candidates who understand implants require monitoring and possible future replacement'],
  },
  'eyelid-surgery': {
    name: 'Eyelid Surgery', tag: 'Plastic Surgery',
    sub: 'Blepharoplasty to remove excess skin, fat, and muscle from upper or lower eyelids — refreshing the eye area and reducing a tired appearance.',
    what: 'Blepharoplasty (eyelid surgery) addresses excess skin, muscle, and fat that accumulate in the upper and/or lower eyelids with age. Upper blepharoplasty removes drooping skin that can impair the visual field. Lower blepharoplasty addresses under-eye bags, puffiness, and hollowness. The procedure is one of the most precise in plastic surgery — subtle changes make a dramatic difference, and surgical artistry is paramount.',
    benefits: [
      { i: '◎', t: 'Refreshed, rested appearance', d: 'Removing excess upper lid skin and lower eye bags eliminates the chronic "tired" look that no amount of sleep or eye cream corrects.' },
      { i: '✦', t: 'Visual field improvement', d: 'Significant upper lid skin excess can obstruct peripheral vision. Blepharoplasty can restore full visual field — sometimes qualifying as functional surgery.' },
      { i: '◈', t: 'Minimal scarring', d: 'Incisions are placed within natural eyelid creases and are virtually invisible once healed.' },
      { i: '⚕', t: 'Long-lasting result', d: 'Unlike non-surgical eye treatments, blepharoplasty delivers permanent structural improvement. Results typically last 10–15 years or more.' },
    ],
    mechanism: 'Upper blepharoplasty: an incision is made within the upper eyelid crease. Excess skin (and sometimes underlying muscle and fat) is excised and the wound is closed with fine sutures — which are removed at 5–7 days. Lower blepharoplasty: a transconjunctival approach (internal incision, no external scar) removes or redistributes fat pockets. For skin excess, a subciliary incision just below the lower lashes is used.',
    expect: { duration: '1–2 hours', sessions: '1 (with follow-up visits)', interval: 'Single procedure' },
    downtime: { level: 'Mild', desc: 'Bruising and swelling for 7–14 days. Most clients are presentable at 10–14 days with makeup. Sutures removed at 5–7 days. No strenuous activity for 2 weeks. Final refined result at 3–6 months.' },
    suitable: ['Adults with excess upper eyelid skin causing a heavy or tired appearance', 'Those with lower eyelid bags or puffiness', 'Anyone with upper lid skin restricting their visual field', 'Adults whose eyelid concerns have not responded to non-surgical approaches'],
  },
  'face-lift': {
    name: 'Face Lift', tag: 'Plastic Surgery',
    sub: 'Rhytidectomy to lift and tighten the face and neck — addressing jowls, deep folds, and skin laxity that non-surgical treatments cannot correct.',
    what: 'A face lift (rhytidectomy) is the definitive surgical solution for moderate-to-significant facial ageing — specifically jowls, deep nasolabial folds, loose neck skin, and loss of jawline definition. At Kaya, we perform SMAS-layer face lifts — addressing the deep structural tissue, not just pulling the skin. This delivers natural, long-lasting results without the tell-tale "windswept" appearance of skin-only techniques.',
    benefits: [
      { i: '✦', t: 'Structural rejuvenation', d: 'SMAS-layer repositioning restores the deep architecture of the face — producing natural results that last 7–10 years or more.' },
      { i: '◎', t: 'Addresses jowls and neck', d: 'Jowling and loose neck skin are structural changes that no injectable, laser, or HIFU can adequately correct. A face lift is the definitive solution.' },
      { i: '◈', t: 'Natural-looking result', d: 'Properly performed, a face lift should make you look like a refreshed, rested version of yourself — not a surgically altered one.' },
      { i: '⚕', t: 'Combination approach', d: 'Face lift is frequently combined with blepharoplasty, fat grafting, or laser resurfacing for comprehensive facial rejuvenation in a single procedure.' },
    ],
    mechanism: 'Incisions are made at the temples, continuing around the ears and into the hairline/behind the ear. The SMAS (the fibromuscular layer beneath the skin) is elevated and repositioned superiorly and posteriorly — correcting descent at the deeper structural level. Skin is then redraped without tension, and excess is removed. A neck lift (platysmaplasty) is typically performed simultaneously for complete lower face and neck rejuvenation.',
    expect: { duration: '3–5 hours', sessions: '1 (with follow-up visits)', interval: 'Single procedure' },
    downtime: { level: 'Significant', desc: '2–3 weeks before appearing in public. Bruising and swelling for 3–4 weeks. Drains for 1–2 days. Sutures removed at 7–10 days. Most clients return to office work at 3 weeks. Full recovery and final result at 3–6 months. Scars are placed to be hidden within hairline and ear contours.' },
    suitable: ['Adults 45+ with moderate-to-significant facial laxity', 'Those with jowling, deep nasolabial folds, or loose neck skin', 'Candidates with realistic expectations and good general health', 'Non-smokers (or those who have quit 6 weeks prior) — smoking significantly impairs wound healing'],
  },
}

export const TREATMENT_SERVICES = {
  dermatology: ['laser-resurfacing', 'botox-fillers', 'chemical-peels', 'microneedling', 'laser-hair-removal', 'prp-hair'],
  slimming: ['cryolipolysis', 'hifu-body', 'radiofrequency', 'contouring-injections', 'mesotherapy', 'pressotherapy'],
  wellness: ['biomarker-testing', 'iv-drip-therapy', 'nad-therapy', 'peptide-protocols', 'hormonal-balance', 'longevity-programme'],
  'plastic-surgery': ['rhinoplasty', 'liposuction', 'tummy-tuck', 'breast-augmentation', 'eyelid-surgery', 'face-lift'],
}
