export const VOUCHERS = [
  {
    id: 'first-visit',
    category: 'discount',
    badge: 'Most Popular',
    badgeStyle: 'popular',
    title: 'First Visit',
    subtitle: '50% off your first treatment',
    price: 149,
    currency: 'AED',
    img: '/Assets/indulgence 2.jpg',
  },
  {
    id: 'gift-500',
    category: 'gift',
    badge: 'Perfect Gift',
    badgeStyle: 'new',
    title: 'Gift Card',
    subtitle: 'AED 500 treatment credit',
    price: 500,
    currency: 'AED',
    img: '/Assets/indulgence 3.jpg',
  },
  {
    id: 'indulgence-1000',
    category: 'gift',
    badge: 'Best Value',
    badgeStyle: 'trending',
    title: 'The Indulgence',
    subtitle: 'AED 1,000 credit + free consultation',
    price: 1000,
    currency: 'AED',
    img: '/Assets/indulgence 1.jpg',
  },
  {
    id: 'wellness-trio',
    category: 'wellness',
    badge: 'Limited Offer',
    badgeStyle: 'new',
    title: 'Wellness Trio',
    subtitle: '3 IV Drip sessions — 30% off',
    price: 890,
    currency: 'AED',
    img: '/Assets/indulgence 4.jpg',
  },
]

export const VOUCHER_FILTERS = [
  { id: 'all',      label: 'All' },
  { id: 'discount', label: 'Discounts' },
  { id: 'gift',     label: 'Gift Cards' },
  { id: 'wellness', label: 'Wellness' },
]
